version: '3'
services:
  behappy-screw-doc:
    restart: 'no'
    privileged: true
    container_name: behappy-screw-doc
    image: wangxiaowu950330/behappy-screw-doc:latest
    # 自定义环境变量
    environment:
      # 是否启用注册(true/false)，默认开启
      REGISTER_ENABLE: true
      # LDAP配置，如需要请配置
      # LDAP_URL: ldap://127.0.0.1:389
      # LDAP_BASE: dc=extension,dc=net
      # LDAP_USERNAME: cn=admin,dc=extension,dc=net
      # LDAP_PASSWORD: 123456
      # 服务本身数据持久化（mysql）
      DATASTORE_BASE: screw_doc
      MYSQL_HOST: 127.0.0.1
      MYSQL_PORT: 3306
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
    ports:
      - "8999:8080"
    volumes:
      # 默认每个数据库生成的html会放在容器内的/user/src/app/doc下，这里将其挂载到宿主机的/opt/dbdoc/doc，你可以自定义挂载宿主机的文件位置
      - /opt/dbdoc/doc:/user/src/app/doc
