version: '3'
services:
  behappy-screw-doc:
    restart: 'no'
    privileged: true
    container_name: behappy-screw-doc
    image: wangxiaowu950330/behappy-screw-doc:latest
    # 自定义环境变量
    environment:
      # 缓存方式,默认为caffeine
      CACHE_TYPE: caffeine
      # REDIS_HOST: 127.0.0.1
      # REDIS_PORT: 9000
      # REDIS_PASSWORD: redis
      # 服务本身数据持久化（mysql）
      DATASTORE_BASE: screw_doc
      MYSQL_HOST: 127.0.0.1
      MYSQL_PORT: 3306
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
    ports:
      - "8999:8080"
    volumes:
      # 默认每个数据库生成的html会放在容器内的/user/src/app/doc下，这里将其挂载到宿主机的/opt/dbdoc/doc，你可以自定义挂载宿主机的文件位置
      - /opt/dbdoc/doc:/user/src/app/doc
