server:
  port: 8080
spring:
  profiles:
    active: @profiles.active@
  ldap:
    urls: ['ldap://localhost:388']
    base: dc=extension,dc=net
    username: cn=admin,${spring.ldap.base}
    password: 123456
    base-environment:
      java:
        naming:
          ldap:
            attributes:
              binary: objectGUID
  # 如果需要使用redis,将此处注释打开
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
  cache:
    type: ${CACHE_TYPE:caffeine}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${DATASTORE_BASE:screw_doc}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
mybatis-plus:
  global-config:
    banner: false
  type-aliases-package: org.xiaowu.behappy.screw.entity
  mapper-locations: classpath:mapper/*.xml
