screw:
  # 多数据源配置, key配置查看DataSourceEnum
  datasource:
    mysql:
      username: xxx
      password: xxx
      ip: xxx
      port: 61148
      driver-class-name: com.mysql.cj.jdbc.Driver
    click_house:
      username: xxx
      password: xxx
      ip: xxx
      port: 9226
      driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
spring:
  # 如果需要使用redis,将此处注释打开
#  redis:
#    host: 139.199.65.191
#    port: 6666
#    password: J*#36@us.tin
  cache:
#    type: redis
    type: caffeine
  datasource:
    url: jdbc:mysql://xxx:xxx/sopei_screw?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: xxx
    password: xxx
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
mybatis-plus:
  global-config:
    banner: false
  type-aliases-package: org.xiaowu.behappy.screw.entity
  mapper-locations: classpath:mapper/*.xml