server:
  port: 8080
spring:
  ldap:
    urls:
      - ${LDAP_URL:ldap://127.0.0.1:389}
    base: ${LDAP_BASE:dc=extension,dc=net}
    username: ${LDAP_USERNAME:cn=admin,dc=extension,dc=net}
    password: ${LDAP_PASSWORD:123456}
    base-environment:
      java:
        naming:
          ldap:
            attributes:
              binary: objectGUID
  cache:
    type: caffeine
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:192.168.56.100}:${MYSQL_PORT:3306}/${DATASTORE_BASE:screw_doc}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
mybatis-plus:
  global-config:
    banner: false
  type-aliases-package: org.xiaowu.behappy.screw.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # handler配置可以省略不写，默认就是这个
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
